name: Check Cities

on:
  push:
    branches:
      - main
    paths:
      - web_source/cities/**
  pull_request:
    branches:
      - main
    paths:
      - web_source/cities/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v46
        id: changed-cities-files
        with:
          base_sha: 'main'
          files: web_source/cities/**/*.md
      - name: Checks travellers links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-cities-files.outputs.all_changed_files }}
        with:
          args: "--no-progress web_source/travellers --verbose  -- ${ALL_CHANGED_FILES}"
          fail: true
          jobSummary: true
